# Generated by Django 5.2.11 on 2026-02-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='artic_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
