# Generated by Django 5.2.11 on 2026-02-19 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_place_artic_id_place_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='place',
            name='project',
        ),
        migrations.RemoveField(
            model_name='place',
            name='visited',
        ),
        migrations.CreateModel(
            name='ProjectPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(null=True)),
                ('visited', models.BooleanField(default=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.place')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
    ]
